In [1]:
%run setup.py build_ext --force

running build_ext
building 'Solver' extension
INFO: C compiler: gcc -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wno-unused -O2 -mmacosx-version-min=11.0

INFO: compile options: '-I/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/numpy/core/include -I/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/include/python3.11 -c'
INFO: gcc: Solver.c


In file included from Solver.c:1214:
In file included from /private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/numpy/core/include/numpy/arrayobject.h:5:
In file included from /private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from /private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/numpy/core/include/numpy/ndarraytypes.h:1948:
/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
Solver.c:75149:26: warning: code will never be executed [-Wunreachable-code]
                module = PyImport_I

INFO: gcc -bundle -undefined dynamic_lookup -L/private/var/tmp/sage-10.0-current/local/lib -Wl,-rpath,/private/var/tmp/sage-10.0-current/local/lib -L/private/var/tmp/sage-10.0-current/local/lib -Wl,-rpath,/private/var/tmp/sage-10.0-current/local/lib -Wl,-platform_version,macos,11.0,11.1 -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -Wl,-rpath,/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib -L. -Wl,-rpath,. -L/private/var/tmp/sage-10.0-current/local/lib -L/private/var/tmp/sage-10.0-current/local/lib -Wl,-rpath,/private/var/tmp/sage-10.0-current/local/lib -L/private/var/tmp/sage-10.0-current/local/lib -Wl,-rpath,/private/var/tmp/sage-10.0-current/local/lib -Wl,-platform_version,macos,11.0,11.1 -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -L/private/var/tmp/sage-10.0-current/local/lib -Wl,-rpath,/private/var/tmp/sage-10.0-current/local/lib build/temp.macosx-11.0-arm64-cpython-311/Solver.o -L/private/var/tmp/sage-10.0-current/loc

10 warnings generated.
ld: warning: passed two min versions (14.0, 11.0) for platform macOS. Using 11.0.
ld: warning: duplicate -rpath '/private/var/tmp/sage-10.0-current/local/lib' ignored
ld: warning: duplicate -rpath '/private/var/tmp/sage-10.0-current/local/lib' ignored
ld: warning: duplicate -rpath '/private/var/tmp/sage-10.0-current/local/lib' ignored
ld: warning: duplicate -rpath '/private/var/tmp/sage-10.0-current/local/lib' ignored


In [2]:
import sys
if "./build/lib.macosx-11.0-arm64-cpython-311/" not in sys.path:
    sys.path.insert(0,"./build/lib.macosx-11.0-arm64-cpython-311/") 
from Solver import InitialData

In [3]:
n = 6 #number of punctures
k = 2 #number of E-branes

I = InitialData(n,k)
print(I.intersections)
print(I.branes)

[[0], [1, 3], [2, 4], [5, 7], [6], [], []]
[[0, 1, 2, 3], [4, 5, 6, 7]]


In [4]:
#I.apply_braid([1,2,1,2])
I.apply_braid([2,2])
#I.apply_braid([-2,4,4,3,3,1,-2,4])
print(I.intersections)
print(I.branes)

[[0], [1, 3, 8, 10, 12, 14], [2, 4], [13, 15, 9, 11, 5, 7], [6], [], []]
[[0, 1, 9, 14, 2, 15], [10, 5, 6, 12, 4, 13]]


In [5]:
#to match LL in Mathematica

thimbles = [item for row in I.intersections for item in row]
branes = [item for row in I.branes for item in row]

for b in copy(thimbles):
    if b not in branes:
        thimbles.remove(b)
        
[[thimbles.index(i)+1 for i in row] for row in I.branes]

[[1, 2, 10, 5, 6, 9], [3, 11, 12, 4, 7, 8]]

In [6]:
testdif = I.one_dimentional_differential(0).as_an_array()
testdif[testdif == None] = 0
#print(testdif)

----------Making the initial approximation----------
d0 squares to zero: False
----------Correcting order 1 in u for brane 0----------
Making the system
We have 3 rows 2 columns
Number of terms to correct: 3
Transfoming to a symmetric square system
Solving the system
Exit_Code: 0
Found a solution!
Correcting 2 matrix elements
Correcting the differential
d0 squares to zero: True


In [7]:
I.make_differential()
dif2d = I.differential.as_an_array()
dif2d[dif2d == None] = 0

----------Making the initial approximation----------
d0 squares to zero: False
----------Correcting order 1 in u for brane 0----------
Making the system
We have 3 rows 2 columns
Number of terms to correct: 3
Transfoming to a symmetric square system
Solving the system
Exit_Code: 0
Found a solution!
Correcting 2 matrix elements
Correcting the differential
d0 squares to zero: True
----------Making the initial approximation----------
d0 squares to zero: False
----------Correcting order 1 in u for brane 1----------
Making the system
We have 3 rows 2 columns
Number of terms to correct: 3
Transfoming to a symmetric square system
Solving the system
Exit_Code: 0
Found a solution!
Correcting 2 matrix elements
Correcting the differential
d0 squares to zero: True
d0 squares to zero: False
d0 squares to zero mod (u,h): True
d0 squares to zero mod (u^2,h): True
d0 squares to zero mod (u^3,h): True
d0 squares to zero mod h: True
d0 squares to zero mod h^2: False
----------Correcting order 1 in h for 

In [8]:
print(dif2d)

[[0 0 0 ... 0 0 0]
 [E_{1, 5}*s4*s3*E_{1, 3} 0 E_{1, 5}*s5*E_{1, 6} ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 -E_{2, 5}*s2*E_{3, 5} 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 -E_{4, 5}*s3*E_{3, 5} 0]]


In [9]:
I.thimbles

{0: Product of T-Thimbles: (1, 3), 0, -1, (0, 4), -1, 2, 3, (0, 10),
 1: Product of T-Thimbles: (1, 5), -1, 1, (0, 13), 1, 2, 5, (0, 5),
 2: Product of T-Thimbles: (1, 6), 0, 1, (0, 15), 1, 2, 6, (0, 6),
 3: Product of T-Thimbles: (1, 3), 1, -2, (0, 5), -2, 2, 3, (0, 12),
 4: Product of T-Thimbles: (1, 4), 2, -2, (0, 8), -2, 2, 4, (0, 4),
 5: Product of T-Thimbles: (1, 5), 1, -1, (0, 9), -1, 2, 5, (0, 13),
 6: Product of T-Thimbles: (2, 3), -1, 0, (1, 4), 0, 2, 3, (1, 10),
 7: Product of T-Thimbles: (2, 5), -2, 2, (1, 13), 2, 2, 5, (1, 5),
 8: Product of T-Thimbles: (2, 6), -1, 2, (1, 15), 2, 2, 6, (1, 6),
 9: Product of T-Thimbles: (2, 3), 0, -1, (1, 5), -1, 2, 3, (1, 12),
 10: Product of T-Thimbles: (2, 4), 1, -1, (1, 8), -1, 2, 4, (1, 4),
 11: Product of T-Thimbles: (2, 5), 0, 0, (1, 9), 0, 2, 5, (1, 13),
 12: Product of T-Thimbles: (5, 2), 0, 1, (11, 4), 1, 1, 2, (9, 10),
 13: Product of T-Thimbles: (4, 5), -1, 2, (11, 13), 2, 2, 5, (9, 5),
 14: Product of T-Thimbles: (4, 6), 0, 2,

In [10]:
I.find_cohomology(QQ)

The number of relevant thimbles: 8


t^2*q^-1 + q + 1 + t^-2*q^2

In [11]:
import sys
if "./build/lib.macosx-11.0-arm64-cpython-311/" not in sys.path:
    sys.path.insert(0,"./build/lib.macosx-11.0-arm64-cpython-311/") 
from Solver import InitialData

In [12]:
n = 6 #number of punctures
k = 2 #number of E-branes

I = InitialData(n,k)
print(I.intersections)
print(I.branes)

[[0], [1, 3], [2, 4], [5, 7], [6], [], []]
[[0, 1, 2, 3], [4, 5, 6, 7]]


In [13]:
I.apply_braid([-2,4,4,3,3,1,-2,4])
print(I.intersections)
print(I.branes)

[[0, 40, 42, 44, 46], [10, 8, 3, 1, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82], [38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 2, 4, 47, 45, 43, 41], [49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 9, 11, 5, 7, 12, 14, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108], [6, 27, 25, 23, 21, 19, 17, 39, 37, 35, 33, 31, 29], [85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109, 15, 13], []]
[[0, 59, 2, 58, 97, 17, 38, 82, 39, 95, 60, 16, 61, 42, 3, 51, 43, 50], [54, 47, 55, 10, 46, 57, 4, 56, 13, 71, 26, 70, 85, 29, 72, 28, 73, 15]]


In [14]:
#to match LL in Mathematica

thimbles = [item for row in I.intersections for item in row]
branes = [item for row in I.branes for item in row]

for b in copy(thimbles):
    if b not in branes:
        thimbles.remove(b)
        
[[thimbles.index(i)+1 for i in row] for row in I.branes]

[[1, 25, 18, 9, 34, 29, 14, 13, 30, 33, 10, 17, 26, 2, 5, 22, 21, 6],
 [7, 20, 23, 4, 3, 24, 19, 8, 36, 27, 16, 11, 32, 31, 12, 15, 28, 35]]

In [15]:
testdif = I.one_dimentional_differential(0).as_an_array()
testdif[testdif == None] = 0
#print(testdif)

----------Making the initial approximation----------
d0 squares to zero: False
----------Correcting order 1 in u for brane 0----------
Making the system
We have 24 rows 23 columns
Number of terms to correct: 10
Transfoming to a symmetric square system
Solving the system
Exit_Code: 0
Found a solution!
Correcting 19 matrix elements
Correcting the differential
d0 squares to zero: True


In [16]:
I.make_differential()
dif2d = I.differential.as_an_array()
dif2d[dif2d == None] = 0

----------Making the initial approximation----------
d0 squares to zero: False
----------Correcting order 1 in u for brane 0----------
Making the system
We have 24 rows 23 columns
Number of terms to correct: 10
Transfoming to a symmetric square system
Solving the system
Exit_Code: 0
Found a solution!
Correcting 19 matrix elements
Correcting the differential
d0 squares to zero: True
----------Making the initial approximation----------
d0 squares to zero: False
----------Correcting order 1 in u for brane 1----------
Making the system
We have 16 rows 19 columns
Number of terms to correct: 8
Zero column in the original matrix: 6
Zero column in the original matrix: 7
Transfoming to a symmetric square system
Solving the system
Exit_Code: 0
Found a solution!
Correcting 13 matrix elements
Correcting the differential
d0 squares to zero: False
----------Correcting order 2 in u for brane 1----------
Making the system
We have 10 rows 9 columns
Number of terms to correct: 3
Transfoming to a symmetr

d0 squares to zero: False
d0 squares to zero mod (u,h): True
d0 squares to zero mod (u^2,h): True
d0 squares to zero mod (u^3,h): True
d0 squares to zero mod h: True
d0 squares to zero mod h^2: False
----------Correcting order 1 in h for the product of the first 2 branes----------
Making the system
We have 82406 rows 29869 columns
Number of terms to correct: 825
Zero column in the original matrix: 10945
Zero column in the original matrix: 16399
Zero column in the original matrix: 16400
Zero column in the original matrix: 16401
Zero column in the original matrix: 19778
Zero column in the original matrix: 19779
Zero column in the original matrix: 26376
Zero column in the original matrix: 26379
Zero column in the original matrix: 26388
Zero column in the original matrix: 26389
Zero column in the original matrix: 26429
Zero column in the original matrix: 26430
Transfoming to a symmetric square system
Solving the system
Exit_Code: 0


AssertionError: Solution is not integral

In [17]:
import sys
if "./build/lib.macosx-11.0-arm64-cpython-311/" not in sys.path:
    sys.path.insert(0,"./build/lib.macosx-11.0-arm64-cpython-311/") 
from Solver import InitialData

In [18]:
n = 6 #number of punctures
k = 2 #number of E-branes

I = InitialData(n,k)
print(I.intersections)
print(I.branes)

[[0], [1, 3], [2, 4], [5, 7], [6], [], []]
[[0, 1, 2, 3], [4, 5, 6, 7]]


In [19]:
I.apply_braid([2,2])
print(I.intersections)
print(I.branes)

[[0], [1, 3, 8, 10, 12, 14], [2, 4], [13, 15, 9, 11, 5, 7], [6], [], []]
[[0, 1, 9, 14, 2, 15], [10, 5, 6, 12, 4, 13]]


In [20]:
#to match LL in Mathematica

thimbles = [item for row in I.intersections for item in row]
branes = [item for row in I.branes for item in row]

for b in copy(thimbles):
    if b not in branes:
        thimbles.remove(b)
        
[[thimbles.index(i)+1 for i in row] for row in I.branes]

[[1, 2, 10, 5, 6, 9], [3, 11, 12, 4, 7, 8]]

In [21]:
testdif = I.one_dimentional_differential(0).as_an_array()
testdif[testdif == None] = 0
#print(testdif)

----------Making the initial approximation----------
d0 squares to zero: False
----------Correcting order 1 in u for brane 0----------
Making the system
We have 3 rows 2 columns
Number of terms to correct: 3
Transfoming to a symmetric square system
Solving the system
Exit_Code: 0
Found a solution!
Correcting 2 matrix elements
Correcting the differential
d0 squares to zero: True


In [22]:
I.make_differential()
dif2d = I.differential.as_an_array()
dif2d[dif2d == None] = 0

----------Making the initial approximation----------
d0 squares to zero: False
----------Correcting order 1 in u for brane 0----------
Making the system
We have 3 rows 2 columns
Number of terms to correct: 3
Transfoming to a symmetric square system
Solving the system
Exit_Code: 0
Found a solution!
Correcting 2 matrix elements
Correcting the differential
d0 squares to zero: True
----------Making the initial approximation----------
d0 squares to zero: False
----------Correcting order 1 in u for brane 1----------
Making the system
We have 3 rows 2 columns
Number of terms to correct: 3
Transfoming to a symmetric square system
Solving the system
Exit_Code: 0
Found a solution!
Correcting 2 matrix elements
Correcting the differential
d0 squares to zero: True
d0 squares to zero: False
d0 squares to zero mod (u,h): True
d0 squares to zero mod (u^2,h): True
d0 squares to zero mod (u^3,h): True
d0 squares to zero mod h: True
d0 squares to zero mod h^2: False
----------Correcting order 1 in h for 

In [23]:
print(dif2d)

[[0 0 0 ... 0 0 0]
 [E_{1, 5}*s4*s3*E_{1, 3} 0 E_{1, 5}*s5*E_{1, 6} ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 -E_{2, 5}*s2*E_{3, 5} 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 -E_{4, 5}*s3*E_{3, 5} 0]]


In [24]:
I.thimbles

{0: Product of T-Thimbles: (1, 3), 0, -1, (0, 4), -1, 2, 3, (0, 10),
 1: Product of T-Thimbles: (1, 5), -1, 1, (0, 13), 1, 2, 5, (0, 5),
 2: Product of T-Thimbles: (1, 6), 0, 1, (0, 15), 1, 2, 6, (0, 6),
 3: Product of T-Thimbles: (1, 3), 1, -2, (0, 5), -2, 2, 3, (0, 12),
 4: Product of T-Thimbles: (1, 4), 2, -2, (0, 8), -2, 2, 4, (0, 4),
 5: Product of T-Thimbles: (1, 5), 1, -1, (0, 9), -1, 2, 5, (0, 13),
 6: Product of T-Thimbles: (2, 3), -1, 0, (1, 4), 0, 2, 3, (1, 10),
 7: Product of T-Thimbles: (2, 5), -2, 2, (1, 13), 2, 2, 5, (1, 5),
 8: Product of T-Thimbles: (2, 6), -1, 2, (1, 15), 2, 2, 6, (1, 6),
 9: Product of T-Thimbles: (2, 3), 0, -1, (1, 5), -1, 2, 3, (1, 12),
 10: Product of T-Thimbles: (2, 4), 1, -1, (1, 8), -1, 2, 4, (1, 4),
 11: Product of T-Thimbles: (2, 5), 0, 0, (1, 9), 0, 2, 5, (1, 13),
 12: Product of T-Thimbles: (5, 2), 0, 1, (11, 4), 1, 1, 2, (9, 10),
 13: Product of T-Thimbles: (4, 5), -1, 2, (11, 13), 2, 2, 5, (9, 5),
 14: Product of T-Thimbles: (4, 6), 0, 2,

In [25]:
I.find_cohomology(QQ)

The number of relevant thimbles: 8


t^2*q^-1 + q + 1 + t^-2*q^2